# Generated by Django 2.1.7 on 2019-11-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termid', models.CharField(max_length=200)),
                ('label', models.CharField(max_length=200)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ControlledVocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=200, unique=True)),
                ('base_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['prefix'],
            },
        ),
        migrations.AddField(
            model_name='controlledterm',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controlled_vocabulary.ControlledVocabulary'),
        ),
        migrations.AlterUniqueTogether(
            name='controlledterm',
            unique_together={('vocabulary', 'termid')},
        ),
    ]
