# Generated by Django 2.1.7 on 2019-12-01 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlledterm',
            options={'ordering': ['termid']},
        ),
        migrations.AlterModelOptions(
            name='controlledvocabulary',
            options={'ordering': ['prefix'], 'verbose_name_plural': 'Controlled vocabularies'},
        ),
    ]
