# Generated by Django 2.2.7 on 2019-12-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlled_vocabulary', '0003_auto_20191202_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlledvocabulary',
            name='concept',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
