# Generated by Django 2.2.7 on 2019-12-11 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("controlled_vocabulary", "0003_auto_20191211_0113"),
    ]

    operations = [
        migrations.RemoveField(model_name="controlledvocabulary", name="test",),
    ]
